// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk4GhJCJ3kZmOX8Ljtnl76CgCkjmxaG9c',
    appId: '1:252781282870:web:0bed7eb6b5675b91affa97',
    messagingSenderId: '252781282870',
    projectId: 'todo-4f5f0',
    authDomain: 'todo-4f5f0.firebaseapp.com',
    storageBucket: 'todo-4f5f0.appspot.com',
    measurementId: 'G-7MNN0BD897',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFHp13ZEbufVbQ2OEPTIbVhzCby5ryRTY',
    appId: '1:252781282870:android:81e199cccecd54ccaffa97',
    messagingSenderId: '252781282870',
    projectId: 'todo-4f5f0',
    storageBucket: 'todo-4f5f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxlfz0wxbd9YnFRH-s8qASMd2mGfrzbBo',
    appId: '1:252781282870:ios:b16a90e7fc021a9faffa97',
    messagingSenderId: '252781282870',
    projectId: 'todo-4f5f0',
    storageBucket: 'todo-4f5f0.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxlfz0wxbd9YnFRH-s8qASMd2mGfrzbBo',
    appId: '1:252781282870:ios:3118db0e65ee6eefaffa97',
    messagingSenderId: '252781282870',
    projectId: 'todo-4f5f0',
    storageBucket: 'todo-4f5f0.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
